name = "tuitionly-modern"
main = ".wrangler/dist/server.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "WAITLIST_KV", id = "your-kv-namespace-id", preview_id = "your-kv-namespace-preview-id" }
]
