name = "tuitionly-modern"
main = ".vercel/output/functions/__next_launcher.func/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = ".vercel/output/static"

[build]
command = "npm run build"

[observability.logs]
enabled = true
